

 var data =   [
    
    {
        "prodName": "Dettol Original Bathing Soap Bar 125gm Each (Buy 4 Get 1 Free)",
        "by": "Reckitt Benckiser",
        "rating": "4.5",
        "review": "229 Ratings & 113 Reviews",
        "higlight": "Germ Protection: Dettol soap protects from 99.99% of germs including viruses and bacteria. Recommended by Indian Medical Association (IMA) Bathing <br> Contains 76% TFM for a rich and creamy lather Natural cleansers: Contains more than 85% naturally derived ingredients and plant-derived cleansers",
        "price": "260",
        "url": "https://onemg.gumlet.io/image/upload/l_watermark_346,w_690,h_700/a_ignore,w_690,h_700,c_pad,q_auto,f_auto/v1631538475/d4ia2vcnwhlocz15jzg4.jpg",
        "description": "Dettol Original Soap is specially formulated to protect you from 100 illness causing germs. It gives 10 times better protection than any ordinary soap. Dettol liquid handwash can help prevent diseases like cold and flu with proper hygiene. ",
        "ingredient": "Glycerin Sodium Palmate Sodium Palm Kemelate Cymbopogon Flexuosus Oil Linalool Coumarin Benzyl Salicylate Citral",
        "benifits": "Germ Protection: Dettol soap protects from 99.99% of germs including viruses and bacteria. Recommended by Indian Medical Association (IMA) Bathing: Contains 76% TFM for a rich and creamy lather Natural cleansers: Contains more than 85% naturally derived ingredients and plant-derived cleansers Dermatologically Tested: Safe on Skin New Pack: Now with a bigger soap bar",
        "direction": "Rub well over the palm, at the back of hand and wash."
    },
    {
        "prodName": "1mg Multivitamin Supreme, Zinc, Calcium and Vitamin D Immunity Booster Capsule",
        "by": "Tata 1mg Healthcare Solutions Private Limited",
        "rating": "4.1",
        "review": "626 Ratings & 388 Reviews",
        "higlight": "Helps to strengthen the immune system  Helps to improve physical fitness and strength Useful in improving memory and concentration Provides essential fatty acids such as EPA & DHA Supports healthy functioning of the cardiovascular system Enriched with multivitamins, multi-minerals, probiotics, ginseng and omega 3 fatty acids",
        "price": "995",
        "url": "https://onemg.gumlet.io/image/upload/l_watermark_346,w_690,h_700/a_ignore,w_690,h_700,c_pad,q_auto,f_auto/v1600699054/cropped/nafthqsf7fsubuushscx.png",
        "description": "1mg Multivitamin Supreme, Zinc, Calcium, and Vitamin D Immunity Booster Capsule is your complete daily health supplement, packed with 25 essential vitamins and minerals that boost immunity, maintains cardiovascular health, improves fitness and strength, enhances memory and concentration and support overall wellbeing.",
        "ingredient": "Vitamins & Amino Acids: Choline Bitartrate, Vitamin B3, Vitamin B1, Folic Acid, Biotin, Vitamin K, Vitamin D3, and Vitamin B12 Minerals: Calcium, Magnesium, Zinc, Potassium, Manganese, Copper, Iodide, Boron Chromium Picolinate, Selenium, Sodium Molybdate Dihydrate Natural Extracts: Omega-3 Marine Triglycerides (33:22), Ginseng, Refined Wheat Germ Oil, Citrus Bioflavonoids, Green Tea Extract, Polyphenols, Grape Seed Extract, Mixed Carotenoids, Ginkgo Biloba, Piperine, and Lutein Probiotics: Lacto Bacillus",
        "benifits": "Helps in boosting the immunity level  Helps in increasing strength and stamina Beneficial in improving memory and concentration Protects from harmful effects of free radicals Supports healthy functioning of the cardiovascular system Helps in improving flexibility and mobility of joints Useful in regulating blood sugar level Provides essential fatty acids such as EPA & DHA Helps in improving the bioavailability of essential nutrients Provides relief from stress and anxiety Helps in maintaining overall health and well being Shelf life: 36 months",
        "direction": "Take one capsule in a day or as directed by the physician."
    },
    {
        "prodName": "Tata 1mg Calcium + Vitamin D3, Zinc, Magnesium and Alfalfa Tablets for Joint Health & Immunity",
        "by": "Tata 1mg Healthcare Solutions Private Limited",
        "rating": "4.2",
        "review": "633 Ratings & 357 Reviews",
        "higlight": "Helps in maintaining healthy bones and teeth Reduces the risk of Osteoporosis and Rickets Helps in preventing calcium deficiency and improves the bio-availability of calcium  Aids in improving the absorption of Calcium in the body Promotes flexibility and mobility of joints Contains Calcium (Calcium citrate maleate 2000 mg), Vitamin D3, Zinc, Magnesium vitamins & minerals ",
        "price": "595",
        "url": "https://onemg.gumlet.io/image/upload/l_watermark_346,w_690,h_700/a_ignore,w_690,h_700,c_pad,q_auto,f_auto/v1637324194/gc3u9gfc331wtsipnljl.jpg",
        "description": "Tata 1mg Calcium + Vitamin D3, Zinc, Magnesium and Alfalfa Tablets for Joint Health & Immunity are beneficial for people who do not get enough calcium from their regular diet. While Calcium is necessary for the normal functioning of nerves, cells, muscles, and bones. Vitamin D helps in the absorption of Calcium in your body. Having the right amount of Calcium and Vitamin D is important for strong bones. The Calcium and Vitamin D3 combination is also beneficial for women who are pregnant, nursing, or in their post-menopausal stage.",
        "ingredient": "Calcium Citrate Malate Vitamin D3 Zinc Magnesium Alfalfa Zinc Vitamin K2-7",
        "benifits": "Calcium and Vitamin-D3 are beneficial for people who do not get enough calcium from their regular diet While Calcium is necessary for the normal functioning of nerves, cells, muscle, and bones, Vitamin-D helps in the absorption of calcium in your body Having the right amounts of Vitamin-D and Calcium is important for strong bones Calcium citrate and Vitamin D3 (Cholecalciferol) improve the bio-availability of calcium Reduces the risk of calcium deficiency, Rickets, and Osteoporosis Promotes mobility and flexibility of joints Helps in reducing the rate of bone loss Decreases risk of fractures in elderly people",
        "direction": "Two tablets per day or as directed by the health care professional."
    },
    {
        "prodName": "Tata 1mg BIS Approved FFP2 N95 Face Mask - Head Loop",
        "by": "Tata 1mg Healthcare Solutions Private Limited",
        "rating": "4.3",
        "review": "9 Ratings & 5 Reviews",
        "higlight": "It offers advanced 5 layer protection from harmful elements It is an Anti-pollution and anti-fog face mask This face mask provides excellent breathability Hypoallergenic, soft and comfortable",
        "price": "190",
        "url": "https://onemg.gumlet.io/image/upload/l_watermark_346,w_690,h_700/a_ignore,w_690,h_700,c_pad,q_auto,f_auto/v1635516003/h3zzgb2tjejohyv3tt2t.jpg",
        "description": "Tata 1mg BIS approved FFP2 N95 Face Mask - Head Loop comprises 5 protective layers. This mask has been rigorously tested and provides excellent protection against bacteria, viruses, pollution and dust. It has a Bacterial Filtration Efficiency (BFE) of up to 99% and Particle Filtration Efficiency (PFE) of up to 95%.  The mask is hypoallergenic and is free of latex, PVC, and silicone, which makes this a viable option for people with sensitivities to these materials. Besides, the mask with the head loop is soft, comfortable, and easy to breathe in. It is lightweight with a soft inner layer for added comfort. Elastic loops are sonic welded inside the outer layers to minimize pressure points.",
        "ingredient": "",
        "benifits": "",
        "direction": "Clean your hands with soap and water or hand sanitizer Put the mask over your nose and mouth by comfortably placing the top loop above the ear and the bottom loop below the ear Make sure your mask fits snugly over your nose, mouth, and chin Bend the nose wire over your nose to fit close to your face Make sure no air is flowing from the area near your eyes or from the sides of the mask Avoid touching the front of the mask when wearing"
    },
    {
        "prodName": "1mg Women's Multivitamin, Zinc, Vitamin C, Calcium, Vitamin D, and Iron Immunity Booster Tablet",
        "by": "Tata 1mg Healthcare Solutions Private Limited",
        "rating": "4.2",
        "review": "223 Ratings & 121 Reviews",
        "higlight": "Supports Bone, Skin and Eye health  Prevents hormonal imbalance  Aids in maintaining a healthy lifestyle  Helps improve immunity  Improves digestion and restore gut bacteria Improves energy levels and supports brain health  A concoction of Multi-Vitamins, Essential Minerals, Women-centric health blend, and Pre & Pro-biotics complex",
        "price": "995",
        "url": "https://onemg.gumlet.io/image/upload/l_watermark_346,w_690,h_700/a_ignore,w_690,h_700,c_pad,q_auto,f_auto/v1632484110/hzqtydexskktgnkgv0f8.jpg",
        "description": "1mg Women's Multivitamin, Zinc, Vitamin C, Calcium, Vitamin D, and Iron  Immunity Booster Tablet is a complete health supplement that supports bone, skin & eye health, prevents hormonal imbalance, and improves immunity. Calcium and Vitamin D3 helps in maintaining healthy bones. Probiotics and prebiotics blend may improve digestion & restore normal flora (gut bacteria). 1mg Women's Multivitamin is useful for a healthy lifestyle for women.",
        "ingredient": "Vitamins: Vitamin C, Vitamin B3, Vitamin E, Vitamin B5, Vitamin B6, Vitamin B2, Vitamin B1, Vitamin A (Retinyl acetate), Vitamin B9 (Folic acid), Vitamin K1, Vitamin B7 (Biotin), Vitamin D2, and Vitamin B12 Minerals: Calcium, Magnesium, Phosphorus, Iron, Zinc, Manganese, Copper, Boron Boron, Proteinate, Iodine, Chromium - Chromium (III) chloride hexahydrate, Selenium - Sodium Selenate, and Molybdenum Sodium molybdate Women Health Blend: Ginkgo biloba leaves ext.- 24% Glycosides, Panax Ginseng root ext.- 10% Ginsenosides, Soya Isoflavone 40%, Garcinia cambogia fruit ext. - 65% HCA, Green coffee bean (Coffea robusta) ext - 45%, chlorogenic acid, L-Lysine HCL, Green tea 98% polyphenols, Citrus Bioflavonoids Extract, Grape (Vitis vinifera) seed extract - 95%, Proanthocyanidin, Lycopene powder, Zeaxanthin 5%, and Lutein Prebiotic & Probiotic Blend: Lactobacillus acidophilus (20 billion Cfu/g), Lactobacillus rhamnosus (20 billion Cfu/g), Bifidobacterium longum (20 billion Cfu/g), Saccharomyces boulardii (20 billion Cfu/g), and Fructooligosaccharides",
        "benifits": "Helps in maintaining healthy bones Useful in maintaining healthy skin and eyes May improve digestion and restore normal flora Aids in enhancing the immunity level of the body  Helps in preventing hormonal imbalance Supports general health and well being in women",
        "direction": "Take one tablet per day or as directed by the healthcare practitioner."
    },
    {
        "prodName": "1mg Salmon Omega 3 Fish Oil Capsule",
        "by": "Tata 1mg Healthcare Solutions Private Limited",
        "rating": "4.4",
        "review": "483 Ratings & 276 Reviews",
        "higlight": "Helps in improving cardiovascular health Aids in boosting memory Supports healthy functioning of the brain Helps in regulating cholesterol levels and high blood pressure Supports flexibility and mobility of joints Helps reduce inflammation  Rich in omega 3 fatty acids EPA and DHA",
        "price": "995",
        "url": "https://onemg.gumlet.io/image/upload/l_watermark_346,w_690,h_700/a_ignore,w_690,h_700,c_pad,q_auto,f_auto/v1600699274/cropped/lc3bohxfl3ounndazqhu.png",
        "description": "1mg Salmon Omega 3 Fish Oil Capsule is enriched with essential fatty acids DHA (Docosahexaenoic acid) and EPA (Eicosapentaenoic acid). It is derived from salmon fish containing essential omega-3 fatty acids which support the healthy functioning of heart and brain. EPA & DHA not only reduces the risk of heart problems by regulating triglycerides and cholesterol levels but also helps in removing extra cholesterol from arterial cells and prevents thickening of the arteries.",
        "ingredient": "Vitamin E Fish Oil Concentrate Eicosapentaenoic Acid (EPA) Docosahexaenoic Acid (DHA) Omega 3",
        "benifits": "Supports healthy functioning of the heart Helps in improving flexibility and mobility of joints Helps in improving the functioning of the brain and enhances memory Omega-3 helps in increasing the level of HDL (good cholesterol) Helps in reducing high blood pressure",
        "direction": "Take one capsule in a day or as directed by the physician."
    },
    {
        "prodName": "Digene Acidity & Gas Relief Gel Orange",
        "by": "Abbott",
        "rating": "4.5",
        "review": "195 Ratings & 103 Reviews",
        "higlight": "Helps relieve bloating, belching, and gas Helps relieve the feeling of discomfort in the stomach Helps treat heartburn (acidity) and indigestion Helps reduce the overall acid level in the stomach",
        "price": "198.23",
        "url": "https://onemg.gumlet.io/image/upload/l_watermark_346,w_690,h_700/a_ignore,w_690,h_700,c_pad,q_auto,f_auto/v1600174116/cropped/pf3vraq88havppemxjar.png",
        "description": "It is used to provide relief from acidity and gas. It provides quick and effective relief from symptoms of belching and bloating that is caused due to gas. It also improves the symptoms of acidity such as abdominal pain and stomach discomfort. It works by neutralizing the stomach acid in the body.  It is an antacid that contains magnesium hydroxide as one of its active ingredients. The magnesium hydroxide dissolves quickly in the stomach and provides quick action. It interacts with the stomach acid to produce magnesium chloride which when absorbed by the body provides rapid relief from acid reflux by neutralizing gastric acid. Also, the presence of aluminum hydroxide neutralizes the acid in the stomach but is known to act slowly. It is also known to inhibit the activity of the enzyme pepsin, thereby helping with heartburn.  This is a sugar-free formulation that provides effective action against acidity, reduces stomach pain, and protects the stomach from making excess acid, helping to provide long-lasting relief. Digene tablets come in a handy pack that can be kept within easy reach at home. It is a scientifically developed combination of active ingredients that provides this medicine a High ANC (Acid Neutralising Capacity) property.   These tablets are usually safe and don’t cause any side effects when taken as per the doctor's recommendation. However, if your symptoms do not improve or if your condition worsens, consult your doctor immediately. Digene Tablet for Acidity and Gas Relief is available in multiple flavors such as orange and mixed fruit along with mint.",
        "ingredient": "Magnesium Hydroxide I.P: 25mg Simethicone I.P: 25mg Magnesium Aluminium Silicate Hydrate: 50mg Dried Aluminum Hydroxide Gel I.P: 300mg",
        "benifits": "Neutralizes excess stomach acid and protects the lining of the stomach from irritation Helps to relieve symptoms of extra gas, such as bloating and discomfort in the stomach Helps to reduce the overall acid level in the stomach Helps in reducing the feeling of indigestion and acidity Reduces gas in the stomach and relieves belching",
        "direction": "Ideally, adults are advised to chew or suck 2-4 tablets 1 hour after meals, preferably at bedtime or as advised by your physician. Children can take the tablets as per their doctor’s recommendation. "
    },
    {
        "prodName": "Brufen Power Pain Relief 800 Sprays",
        "by": "Abbott",
        "rating": "4.2",
        "review": "86 Ratings & 40 Reviews",
        "higlight": "Provides powerful relief from pain with 2% diclofenac Provides targeted pain relief with its precision nozzle with 1 shot technology Provides effective relief from back pain, joint pain, muscle pain, shoulder and neck pain Provides 800 sprays in the 40g pack and 400 sprays in the 20g pack",
        "price": "150",
        "url": "https://onemg.gumlet.io/image/upload/l_watermark_346,w_690,h_700/a_ignore,w_690,h_700,c_pad,q_auto,f_auto/v1601905269/uxo7tprhsif0fk99o4is.jpg",
        "description": "Brufen Power Metered Pain Relief Spray is a metered pain relief spray with double strength* of Diclofenac for powerful pain relief and a precision nozzle with 1 shot technology that allows only a limited amount of product to be released thus ensuring low wastage. Provides effective relief from back pain, joint pain, muscle pain, shoulder and neck pain. Available in value for money packs - 40g (800 sprays) and 20g (400 sprays).",
        "ingredient": "Diclofenac diethylamine I.P - 2.32%w/v Equivalent to Diclofenac sodium I.P. 2% w/v Methyl salicylate I.P 10% w/v Menthol I.P 5% w/v",
        "benifits": "Diclofenac Diethylamine I.P 2.32% provides  powerful pain relief Methyl Salicylate I.P 10% helps to relieve discomfort and pain by its counter-irritant action Menthol I.P 5% helps to relieve pain by its cooling effect Provides powerful pain relief with double strength* of Diclofenac It has a metered spray to ensure low wastage+ Provides targeted pain relief with its precision nozzle with 1 shot technology  Provides effective relief from backache, joint pain, muscle, shoulder, neck pain and total ortho care",
        "direction": "Shake well before use. Press nozzle only once for spray, keeping the nozzle 5 to 10cm away from the affected area Do not spray on open wounds. Use up to 3 times a day"
    },
    {
        "prodName": "Digene Gel On The Go Stick Pack (10ml Each) Mint",
        "by": "Abbott",
        "rating": "4.6",
        "review": "34 Ratings & 17 Reviews",
        "higlight": "Aid to alleviate bloating, belching and gas Helps ease the sensation of abdominal pain Relieve acidity, indigestion and heartburn Reduces the total stomach acid level",
        "price": "31.5",
        "url": "https://onemg.gumlet.io/image/upload/l_watermark_346,w_690,h_700/a_ignore,w_690,h_700,c_pad,q_auto,f_auto/v1629309842/i9uw97bk1msa2mlihv1m.jpg",
        "description": "Digene Gel On The Go Pack provides relief from acidity and gas whenever acidity strikes. It has the same formulation as your trusted Digene Gel in a convenient pack with no water or glass needed.Squeeze, tear and drink for effective relief from acidity. Its scientifically developed combination of active ingredients provides a High ANC (Acid Neutralising Capacity) property. Get quick relief from acidity, gas, heartburn, bloated stomach and uneasiness.*Available in Mint & Orange flavours.",
        "ingredient": "Magnesium Hydroxide I.P: 185mg Simethicone I.P: 50mg Sodium carboxymethylcellulose: 100mg Dried Aluminum Hydroxide Gel I.P: 300mg",
        "benifits": "Neutralizes excess acidity in the stomach and prevents irritation Helps to alleviate further gas symptoms such as bloating and gastrointestinal pain Helps to lower the acidity of the stomach Aid to lessen the sense of indigestion and acidity Reduces stomach gas and loosens the stomach",
        "direction": "How To Use: Have Digene Gel on-the-go in 3 Easy Steps: Squeeze, Tear & Drink. No water or glass required. Dosage: Adults: Single dose for adults only. 1 Stick Pack (10ml) after meals or as directed by the Physician.Children: As advised by the physician"
    },
    {
        "prodName": "Digene Acidity & Gas Relief Tablet Multi Flavours",
        "by": "Abbott",
        "rating": "4.5",
        "review": "353 Ratings & 155 Reviews",
        "higlight": "Helps to relieve bloating, belching, and gas Helps to relieve the feeling of discomfort in the stomach Helps to treat heartburn (acidity) and indigestion Helps to reduce the overall acid level in the stomach",
        "price": "21.95",
        "url": "https://onemg.gumlet.io/image/upload/l_watermark_346,w_690,h_700/a_ignore,w_690,h_700,c_pad,q_auto,f_auto/v1600689355/vhdx2ta9nmzpbbdpeybi.jpg",
        "description": "It is used to provide relief from acidity and gas whenever acidity strikes. It is also known to provide quick and effective relief from gas troubles such as bloating and belching. It also helps to improve the symptoms of acidity such as abdominal pain and stomach discomfort. It works by neutralizing the stomach acid in the body.  It is an antacid that contains magnesium hydroxide as one of its active ingredients. It dissolves quickly in the stomach and provides quick action. It interacts with stomach acid to produce magnesium chloride which is absorbed by the body. It provides rapid relief from acid reflux by neutralizing gastric acid. Also, the presence of aluminum hydroxide neutralizes the acid in the stomach but is known to act slowly. It is also known to inhibit the activity of the enzyme pepsin thereby helping with heartburn.  It has a sugar-free formulation that provides effective action against acidity, reduces stomach pain, and protects the stomach from making excess acid for long-lasting relief. Digene tablets come in a handy pack that can be kept within easy reach at home. It's scientifically developed combination of active ingredients provides a high ANC (Acid Neutralising Capacity) property.   These tablets are usually safe and don’t cause any side effects when taken as per the doctor's recommendation. However, if your symptoms do not improve or if your condition worsens, then consult your doctor immediately. Digene Tablet for Acidity & Gas Relief is available in Mint, Orange, Mixed Fruit, and Multi flavors.",
        "ingredient": "Magnesium Hydroxide I.P: 25mg Simethicone I.P: 25mg Magnesium Aluminium Silicate Hydrate: 50mg Dried Aluminum Hydroxide Gel I.P: 300mg",
        "benifits": "Neutralizes excess stomach acid and protects the lining of the stomach from irritation Helps to relieve symptoms of extra gas such as, bloating and feeling of discomfort in the stomach Helps to reduce the overall acid level in the stomach It helps in reducing the feeling of indigestion and acidity It is used in treating the gas and belching in the stomach",
        "direction": "Ideally, adults are advised to chew or suck 2-4 tablets, after meals, preferably at bedtime or as advised by your physician. Children can take the tablets as per their doctor’s recommendation. "
    },
    {
        "prodName": "Nivea Naturally Good Body Lotion Natural Lavender",
        "by": "Nivea India Pvt Ltd",
        "rating": "4.2",
        "review": "9 Ratings & 5 Reviews",
        "higlight": "",
        "price": "399",
        "url": "https://onemg.gumlet.io/image/upload/l_watermark_346,w_690,h_700/a_ignore,w_690,h_700,c_pad,q_auto,f_auto/v1624044214/jjike2ciy7sl7wtuzzry.jpg",
        "description": "Nivea Naturally Good Body Lotion Natural Lavender is good for the skin and good for the environment, as it includes 98% natural components for healthy, attractive skin and is packaged in an environmentally responsible manner with 50% less plastic which reduces the impact on nature. Nivea Naturally Good Natural Lavender Body lotion contains natural Lavender extracts that provide long-lasting moisturization and relaxing fragrance. It is suitable for dry skin.",
        "ingredient": "Glycerin Alcohol Denat. 6.1%v/v Cetearyl Alcohol Coco-Caprylate/Caprate Cocoglycerides Glyceryl Stearate SE Dicaprylyl Ether Lavandula Angustifolia Flower Extract Hydroxypropyl Starch Phosphate Xanthan Gum Cetyl Palmitate Glyceryl Stearate Sodium Cetearyl Sulfate Tocopherol Citric Acid Caprylyl Glycol Ethylhexylglycerin Hydroxyacetophenone Benzyl Alcohol Parfum",
        "benifits": "Helps to balance the skin and is suitable for dry and very dry skin Provides hydration up to 48 hours Contains 98% ingredients of natural origin Contains 2% essential ingredients for formula stability and fragrance Bottle contains 50% less plastic Squeeze and roll up bottle to use till the last drop and avoid wastage Clean formula with no parabens, mineral oils and microplastics",
        "direction": "Step 1- Dispense the body lotion into the palm of your hand Step 2- Gently massage the lotion onto your skin Step 3- Apply evenly all over the body Step 4- Use daily to give your skin the perfect results"
    },
    {
        "prodName": "Zandu Ortho Vedic Knee & Joint Pain Oil",
        "by": "Emami Ltd",
        "rating": "4.1",
        "review": "10 Ratings",
        "higlight": "It gives a visible improvement in 7 days It provides quick and long-lasting relief It has the power of Mahanarayan oil",
        "price": "295",
        "url": "https://onemg.gumlet.io/image/upload/l_watermark_346,w_690,h_700/a_ignore,w_690,h_700,c_pad,q_auto,f_auto/v1631190246/asqryelbmu85zqqovpdu.jpg",
        "description": "Zandu Ortho Vedic Knee & Joint Pain Oil is the 1st knee and joint pain relief oil from the house of Zandu - the Pain Management expert. It gives a visible improvement in just 7 days and helps improve the mobility of joints and muscles by giving quick and long-lasting relief.",
        "ingredient": "Mahamash tail Mahanarayan tail Vishgarbha tail Gandhpuro tail",
        "benifits": "It gives a visible improvement in 7 days It provides quick and long-lasting relief It has the power of Mahanarayan oil It does not have side effects",
        "direction": "Spread out 5-10ml of Zandu Ortho Vedic Oil on the inflamed part and gently massage for a few minutes Use twice daily in case of severe pain. Repeat as often as required. Do not apply hot fomentation"
    },
    {
        "prodName": "Horlicks Health and Nutrition Drink Classic Malt",
        "by": "Hindustan Unilever Ltd",
        "rating": "4.4",
        "review": "137 Ratings & 57 Reviews",
        "higlight": "Helps to increase calcium in bones of children Aids to improve the memory of the children Contains essential nutrients for overall development",
        "price": "375",
        "url": "https://onemg.gumlet.io/image/upload/l_watermark_346,w_690,h_700/a_ignore,w_690,h_700,c_pad,q_auto,f_auto/v1613566796/iheqzrewt0n4auxbd2l6.jpg",
        "description": "Horlicks Health And Nutrition Drink is a nourishing beverage which is part of the balanced diet.",
        "ingredient": "Malted barley (extracted solids) 39% Wheat flour (27%) Milk solids (14%) Minerals Wheat gluten (2%) Vitamins Protein isolat",
        "benifits": "Increases the density of minerals such as calcium in bones to give children bigger and stronger bones Horlicks is clinically proven to increase lean tissue, making children stronger Helps improve attention and concentration to make the child smarter Clinically proven for more hemopoietic nutrients in the blood and to increase fat-free mass, making the child stronger",
        "direction": "As per the requirement or as directed."
    },
    {
        "prodName": "Cadbury Bournvita Health Drink",
        "by": "Mondelez India Foods Ltd",
        "rating": "4.5",
        "review": "429 Ratings & 243 Reviews",
        "higlight": "Helps to strengthen the bones Helps to fortify the immune system Facilitates overall vision development Helps to enhance the metabolism Promotes overall growth and development",
        "price": "223",
        "url": "https://onemg.gumlet.io/image/upload/l_watermark_346,w_690,h_700/a_ignore,w_690,h_700,c_pad,q_auto,f_auto/v1600089136/cropped/xrrnuoyv97tdejpkngdm.png",
        "description": "Cadbury Bournvita Health Drink is a malted drink mix which contains a unique blend of Vitamin (D, B2, B9, B12) Iron and Calcium. Formulated with rich chocolate flavour it helps in providing essential nutrients and minerals which promote physical and mental development. It has been clinically proven to increase the levels of vitamins and iron in our body. It makes a nutritious drink with milk and can be consumed as both hot and cold drink.",
        "ingredient": "Malt Extract  Sugar  Cocoa Solids Liquid Glucose Emulsifiers Raising agent Vitamins & Minerals ",
        "benifits": "Contains essential vitamins and minerals Helps in developing strong bones Helps in maintaining normal vision Promotes circulation of oxygen in the blood  Boosts immunity and improves metabolism Provides essential mental development",
        "direction": "Take 1-2 teaspoons of Bournvita and add to a cup of hot or cold milk with sugar. Suggested to take two times a day for best results."
    }
]

localStorage.setItem("champData",JSON.stringify(data));