

 var data =   [
    
    {
        "productName": "1mg Multivitamin Supreme, Zinc, Calcium and Vitamin D Immunity Booster Capsule",
        "productby": "Tata 1mg Healthcare Solutions Private Limited",
        "rating": "4.1",
        "review": "626 Ratings & 388 Reviews",
        "prodHeading1": "Helps to strengthen the immune system ",
        "prodHeading2": "Helps to improve physical fitness and strength",
        "prodHeading3": "Useful in improving memory and concentration",
        "price": "995",
        "discount": "50",
        "url": "https://onemg.gumlet.io/image/upload/l_watermark_346,w_690,h_700/a_ignore,w_690,h_700,c_pad,q_auto,f_auto/v1600699054/cropped/nafthqsf7fsubuushscx.png",
        "description1": "1mg Multivitamin Supreme, Zinc, Calcium, and Vitamin D Immunity Booster Capsule",
        "description2": "is your complete daily health supplement, packed with 25 essential vitamins and minerals that boost immunity, maintains cardiovascular health, improves fitness and strength, enhances memory and concentration and support overall wellbeing.",
        "keyIngredient1": "Vitamins & Amino Acids:",
        "keyIngredient2": "Choline Bitartrate, Vitamin B3, Vitamin B1, Folic Acid, Biotin, Vitamin K, Vitamin D3, and Vitamin B12",
        "keyIngredient3": "Minerals:",
        "keyIngredient4": "Calcium, Magnesium, Zinc, Potassium, Manganese, Copper, Iodide, Boron Chromium Picolinate, Selenium, Sodium Molybdate Dihydrate",
        "keyIngredient5": "Natural Extracts:",
        "keyIngredient6": "Omega-3 Marine Triglycerides (33:22), Ginseng, Refined Wheat Germ Oil, Citrus Bioflavonoids, Green Tea Extract, Polyphenols, Grape Seed Extract, Mixed Carotenoids, Ginkgo Biloba, Piperine, and Lutein",
        "keyIngredient7": "Probiotics: Lacto Bacillus",
        "keyBenefit1": "Helps in boosting the immunity level ",
        "keyBenefit2": "Helps in increasing strength and stamina",
        "keyBenefit3": "Beneficial in improving memory and concentration",
        "keyBenefit4": "Protects from harmful effects of free radicals",
        "keyBenefit5": "Supports healthy functioning of the cardiovascular system",
        "directionUse": "Take one capsule in a day or as directed by the physician.",
        "safetyInfo1": "Read the label carefully before use",
        "safetyInfo2": "Keep out of reach of children",
        "safetyInfo3": "Keep the container tightly closed"
    },
    {
        "productName": " Tata 1mg Calcium + Vitamin D3, Zinc, Magnesium and Alfalfa Tablets for Joint Health & Immunity",
        "productby": "Tata 1mg Healthcare Solutions Private Limited",
        "rating": "4.2",
        "review": "633 Ratings & 357 Reviews",
        "prodHeading1": "Helps in maintaining healthy bones and teeth",
        "prodHeading2": "Reduces the risk of Osteoporosis and Rickets",
        "prodHeading3": "Helps in preventing calcium deficiency and improves the bio-availability of calcium ",
        "price": "595",
        "discount": "50",
        "url": "https://onemg.gumlet.io/image/upload/l_watermark_346,w_690,h_700/a_ignore,w_690,h_700,c_pad,q_auto,f_auto/v1637324194/gc3u9gfc331wtsipnljl.jpg",
        "description1": "Tata 1mg Calcium + Vitamin D3, Zinc, Magnesium and Alfalfa Tablets for Joint Health & Immunity",
        "description2": " are beneficial for people who do not get enough calcium from their regular diet. While Calcium is necessary for the normal functioning of nerves, cells, muscles, and bones. Vitamin D helps in the absorption of Calcium in your body. Having the right amount of Calcium and Vitamin D is important for strong bones. The Calcium and Vitamin D3 combination is also beneficial for women who are pregnant, nursing, or in their post-menopausal stage.",
        "keyIngredient1": "Calcium Citrate Malate",
        "keyIngredient2": "Vitamin D3",
        "keyIngredient3": "Zinc",
        "keyIngredient4": "Magnesium",
        "keyIngredient5": "Alfalfa",
        "keyIngredient6": "Zinc",
        "keyIngredient7": "Vitamin K2-7",
        "keyBenefit1": "Calcium and Vitamin-D3 are beneficial for people who do not get enough calcium from their regular diet",
        "keyBenefit2": "While Calcium is necessary for the normal functioning of nerves, cells, muscle, and bones, Vitamin-D helps in the absorption of calcium in your body",
        "keyBenefit3": "Having the right amounts of Vitamin-D and Calcium is important for strong bones",
        "keyBenefit4": "Calcium citrate and Vitamin D3 (Cholecalciferol) improve the bio-availability of calcium",
        "keyBenefit5": "Reduces the risk of calcium deficiency, Rickets, and Osteoporosis",
        "directionUse": "Two tablets per day or as directed by the health care professional.",
        "safetyInfo1": "Shelf Life: 18 months ",
        "safetyInfo2": "Read the label carefully before use",
        "safetyInfo3": "Pregnant/lactating women and children with medical conditions should consult a health care practitioner before use"
    },
    {
        "productName": "1mg Women's Multivitamin, Zinc, Vitamin C, Calcium, Vitamin D, and Iron Immunity Booster Tablet",
        "productby": "Tata 1mg Healthcare Solutions Private Limited",
        "rating": "4.2",
        "review": "223 Ratings & 121 Reviews",
        "prodHeading1": "Supports Bone, Skin and Eye health ",
        "prodHeading2": "Prevents hormonal imbalance",
        "prodHeading3": "A concoction of Multi-Vitamins, Essential Minerals, Women-centric health blend, and Pre & Pro-biotics complex",
        "price": "995",
        "discount": "50%",
        "url": "https://onemg.gumlet.io/image/upload/l_watermark_346,w_690,h_700/a_ignore,w_690,h_700,c_pad,q_auto,f_auto/v1632484110/hzqtydexskktgnkgv0f8.jpg",
        "description1": "1mg Women's Multivitamin, Zinc, Vitamin C, Calcium, Vitamin D, and Iron  Immunity Booster Tablet",
        "description2": " is a complete health supplement that supports bone, skin & eye health, prevents hormonal imbalance, and improves immunity. Calcium and Vitamin D3 helps in maintaining healthy bones. Probiotics and prebiotics blend may improve digestion & restore normal flora (gut bacteria). 1mg Women's Multivitamin is useful for a healthy lifestyle for women.",
        "keyIngredient1": "Vitamins:",
        "keyIngredient2": "Vitamin C, Vitamin B3, Vitamin E, Vitamin B5, Vitamin B6, Vitamin B2, Vitamin B1, Vitamin A (Retinyl acetate), Vitamin B9 (Folic acid), Vitamin K1, Vitamin B7 (Biotin), Vitamin D2, and Vitamin B12",
        "keyIngredient3": "Minerals:",
        "keyIngredient4": "Calcium, Magnesium, Phosphorus, Iron, Zinc, Manganese, Copper, Boron Boron, Proteinate, Iodine, Chromium - Chromium (III) chloride hexahydrate, Selenium - Sodium Selenate, and Molybdenum Sodium molybdate",
        "keyIngredient5": "Women Health Blend:",
        "keyIngredient6": "Ginkgo biloba leaves ext.- 24% Glycosides, Panax Ginseng root ext.- 10% Ginsenosides, Soya Isoflavone 40%, Garcinia cambogia fruit ext. - 65% HCA, Green coffee bean (Coffea robusta) ext - 45%, chlorogenic acid, L-Lysine HCL, Green tea 98% polyphenols, Citrus Bioflavonoids Extract, Grape (Vitis vinifera) seed extract - 95%, Proanthocyanidin, Lycopene powder, Zeaxanthin 5%, and Lutein",
        "keyIngredient7": "Lactobacillus acidophilus (20 billion Cfu/g), Lactobacillus rhamnosus (20 billion Cfu/g), Bifidobacterium longum (20 billion Cfu/g), Saccharomyces boulardii (20 billion Cfu/g), and Fructooligosaccharides",
        "keyBenefit1": "Helps in maintaining healthy bones",
        "keyBenefit2": "Useful in maintaining healthy skin and eyes",
        "keyBenefit3": "May improve digestion and restore normal flora",
        "keyBenefit4": "Aids in enhancing the immunity level of the body ",
        "keyBenefit5": "Helps in preventing hormonal imbalance",
        "directionUse": "Take one tablet per day or as directed by the healthcare practitioner.",
        "safetyInfo1": "Shelf Life: 18 months ",
        "safetyInfo2": "Read the label carefully before use",
        "safetyInfo3": "Keep out of the reach of children"
    },
    {
        "productName": "1mg Hydration Drink Mix Electrolytes Orange",
        "productby": "Tata 1mg Healthcare Solutions Private Limited",
        "rating": "4.4",
        "review": "9 Ratings",
        "prodHeading1": "Rehydrates faster than water",
        "prodHeading2": "Maintains hydration more effectively than plain water",
        "prodHeading3": "Maintains fluid and electrolyte balance",
        "price": "645",
        "discount": "31",
        "url": "https://onemg.gumlet.io/image/upload/l_watermark_346,w_690,h_700/a_ignore,w_690,h_700,c_pad,q_auto,f_auto/v1631892447/xujapwjw6thc8yxcmnwm.jpg",
        "description1": "1mg Hydration Drink Mix Electrolytes",
        "description2": " is a nutritious drink containing dextrose, sucrose, sodium, potassium and magnesium. It helps to maintain fluid and electrolyte balance. The presence of Vitamin B6 and B12 supports the body's immune system while taurine and inositol enhance concentration and physical performance. It comes in a refreshing orange flavour.",
        "keyIngredient1": "Dextrose",
        "keyIngredient2": "Sucrose",
        "keyIngredient3": "Sodium",
        "keyIngredient4": "Potassium",
        "keyIngredient5": "Magnesium",
        "keyIngredient6": "",
        "keyIngredient7": "",
        "keyBenefit1": "Rehydrates faster than water",
        "keyBenefit2": "Maintains hydration more effectively than plain water",
        "keyBenefit3": "Maintains fluid and electrolyte balance",
        "keyBenefit4": "Contains vitamin B6 and B12 to support the body's immune system",
        "keyBenefit5": "Vitamin B12, taurine and inositol enhance concentration and physical performance",
        "directionUse": "Mix 2 full scoops (30g approx) in 250 ml of water",
        "safetyInfo1": "Read the label carefully before use",
        "safetyInfo2": "Store in a cool and dry place away from direct sunlight",
        "safetyInfo3": "Keep out of reach of the children"
    },
    {
        "productName": "Digene Acidity & Gas Relief Gel Orange",
        "productby": "Abbott",
        "rating": "4.5",
        "review": "195 Ratings & 103 Reviews",
        "prodHeading1": "Helps relieve bloating, belching, and gas",
        "prodHeading2": "Helps relieve the feeling of discomfort in the stomach",
        "prodHeading3": "Helps treat heartburn (acidity) and indigestion",
        "price": "198.23",
        "discount": "18",
        "url": "https://onemg.gumlet.io/image/upload/l_watermark_346,w_690,h_700/a_ignore,w_690,h_700,c_pad,q_auto,f_auto/v1600174116/cropped/pf3vraq88havppemxjar.png",
        "description1": "",
        "description2": "It is used to provide relief from acidity and gas. It provides quick and effective relief from symptoms of belching and bloating that is caused due to gas. It also improves the symptoms of acidity such as abdominal pain and stomach discomfort. It works by neutralizing the stomach acid in the body.",
        "keyIngredient1": "Magnesium Hydroxide I.P: 25mg",
        "keyIngredient2": "Simethicone I.P: 25mg",
        "keyIngredient3": "Magnesium Aluminium Silicate Hydrate: 50mg",
        "keyIngredient4": "Dried Aluminum Hydroxide Gel I.P: 300mg",
        "keyIngredient5": "",
        "keyIngredient6": "",
        "keyIngredient7": "",
        "keyBenefit1": "Neutralizes excess stomach acid and protects the lining of the stomach from irritation",
        "keyBenefit2": "Helps to relieve symptoms of extra gas, such as bloating and discomfort in the stomach",
        "keyBenefit3": "Helps to reduce the overall acid level in the stomach",
        "keyBenefit4": "Helps in reducing the feeling of indigestion and acidity",
        "keyBenefit5": "Reduces gas in the stomach and relieves belching",
        "directionUse": "Ideally, adults are advised to chew or suck 2-4 tablets 1 hour after meals, preferably at bedtime or as advised by your physician. Children can take the tablets as per their doctor’s recommendation.",
        "safetyInfo1": "Read the label carefully before use.",
        "safetyInfo2": "Keep out of reach of the children.",
        "safetyInfo3": "Do not exceed the recommended dosage."
    }
  
]

localStorage.setItem("champData",JSON.stringify(data));